### ISSUE TITLE
Uncaught Error: Call to private method ... PageHelper::strip()

### ISSUE THREAD

**Issue by jackhogg** [justbetter/magento2-algolia-wordpress-integration#1]
```
PHP Fatal error:  Uncaught Error: Call to private method Algolia\AlgoliaSearch\Helper\Entity\PageHelper::strip() from context 'JustBetter\AlgoliaWordpressIntegration\Helper\Entity\PageHelper' in .../vendor/just-better/magento2-algolia-wordpress-integration/Helper/Entity/PageHelper.php
```

There seems to be an issue with the strip method preformed in the 'content' area, of the data processing, that I can't seem to resolve on my own. Is there a better way to reference this method?

**Comment by royduin** [comment]
I'm currently with vacation, maybe my colleague @rakibabu can look into this, if not I'll come back to you next week.

**Comment by rakibabu** [comment]
Hi @jackhogg,

I'll check this issue this week.

**Comment by royduin** [comment]
Fixed: https://github.com/justbetter/magento2-algolia-wordpress-integration/pull/2, @jackhogg; please let us know if it's working now.
